name: Release macOS Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release-macos:
    runs-on: macos-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install dependencies (Homebrew & raylib)
        run: |
          brew update
          brew install raylib pkg-config

      - name: Build
        run: make build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin/osx/game
          asset_name: game
          asset_content_type: application/octet-stream
