#ifndef FLAGS_H
#define FLAGS_H

typedef struct {
    bool showFPS;
} Flags;

const char* raylibFlags[] = {
    "FLAG_VSYNC_HINT",
    "FLAG_FULLSCREEN_MODE",
    "FLAG_WINDOW_RESIZABLE",
    "FLAG_WINDOW_UNDECORATED",
    "FLAG_WINDOW_HIDDEN",
    "FLAG_WINDOW_MINIMIZED",
    "FLAG_WINDOW_MAXIMIZED",
    "FLAG_WINDOW_UNFOCUSED",
    "FLAG_WINDOW_TOPMOST",
    "FLAG_WINDOW_ALWAYS_RUN",
    "FLAG_WINDOW_TRANSPARENT",
    "FLAG_WINDOW_HIGHDPI",
    "FLAG_WINDOW_MOUSE_PASSTHROUGH",
    "FLAG_BORDERLESS_WINDOWED_MODE",
    "FLAG_MSAA_4X_HINT",
    "FLAG_INTERLACED_HINT"
};

#endif // FLAGS_H
